# Generated by Django 4.1 on 2024-03-07 11:40

import django.contrib.auth.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useractivatetokens'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='useractivatetokens',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
